### ISSUE TITLE
Respond to keyword lists and maps?

### ISSUE THREAD

**Issue by plicjo** [mrmicahcooper/ecto_factory#10]
The `attrs` and `schema` functions respond to keyword lists: https://github.com/mrmicahcooper/ecto_factory/blob/master/lib/ecto_factory.ex#L48

What do you think about them also responding to a `Map` also @mrmicahcooper?

**Comment by mrmicahcooper** [comment]
Yeah a `Map` would also work great.

Historical context: I started with a Keyword list so it would look more like conventional config when you set defaults in your `/config` files. 

You could make new `attrs` and `schema` that takes a map, converts to a Keyword and passes it on if you like. Or make `build_attrs` handle both keywords and maps.

If you don't have the time. I'll add it in when I get a chance.

**Comment by plicjo** [comment]
I'll make a P/R now!
