### ISSUE TITLE
Attrs map return atom keys instead of string keys?

### ISSUE THREAD

**Issue by plicjo** [mrmicahcooper/ecto_factory#15]
https://github.com/mrmicahcooper/ecto_factory/blob/master/test/ecto_factory_test.exs#L40-L50

The `attrs` function returning String keys is not standard. Atom keys are standard.

Is it possible to default to atom keys instead for the map?

**Comment by plicjo** [comment]
Discussion on the matter: https://elixirforum.com/t/map-key-is-a-atom-or-string/13285/9

**Comment by mrmicahcooper** [comment]
Yes I've been thinking about this actually. 
I'd like to have both. Personally, I use the `attrs` in controller tests where the keys are strings. But in other cases ,it's a pain.

Perhaps we add an option to `attrs` to get atoms or have another function for it?

Can you think of an elegant solution?

If we're worried about crashing the VM we could always utilize `String.to_existing_atom/1`, too!

**Comment by plicjo** [comment]
@mrmicahcooper Solid. Will look into this

**Comment by plicjo** [comment]
@mrmicahcooper Thoughts?

**Comment by mrmicahcooper** [comment]
Fixed by https://github.com/mrmicahcooper/ecto_factory/pull/17
